// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func projectSetup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card bg-base-100 shadow-xl mb-12 border border-base-300\"><div class=\"card-body p-4 sm:p-8\"><div class=\"flex items-center gap-4 mb-4\"><div class=\"badge badge-primary badge-lg font-bold text-white\">1</div><h3 id=\"project-setup\" class=\"card-title text-2xl\">Setting Up Your Project</h3></div><div class=\"prose max-w-none\"><p>We provide official SDKs for multiple languages that handle the underlying network protocols, serialization, and game loop timing. We highly recommend using one of these SDKs so you can focus purely on your bot's algorithmic design.</p><ul><li><a class=\"link link-primary\" href=\"/docs/GolangSDK\">Golang SDK Tutorial</a></li><li><a class=\"link link-primary\" href=\"/docs/PythonSDK\">Python SDK Tutorial</a></li><li><a class=\"link link-primary\" href=\"/docs/TypeScriptSDK\">TypeScript SDK Tutorial</a></li><li><a class=\"link link-primary\" href=\"/docs/RustSDK\">Rust SDK Tutorial</a></li></ul><p>Simply follow the respective tutorial to initialize a new project and install the SDK package.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
